#!/bin/bash
# FaceSudo installer: creates the venv, downloads optional models, generates
# launcher scripts, and installs the .zshrc sudo wrapper.
#
# Usage:
#   ./install.sh                standard install
#   ./install.sh --download-68  also fetch the 68-point landmark model (~96 MB)
#
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV="$PROJECT_DIR/.venv"
CONFIG_DIR="$HOME/.facesudo"
BIN_DIR="$CONFIG_DIR/bin"
MODELS_DIR="$CONFIG_DIR/models"

echo "== FaceSudo installer =="

# 1. Virtualenv -----------------------------------------------------------
if [ ! -x "$VENV/bin/python" ]; then
    echo "[1/4] Creating virtualenv..."
    if command -v /usr/local/bin/python3.12 >/dev/null 2>&1; then
        /usr/local/bin/python3.12 -m venv "$VENV"
    else
        python3.12 -m venv "$VENV"
    fi
else
    echo "[1/4] Virtualenv already present."
fi

echo "[2/4] Installing dependencies (dlib compiles from source; may take several minutes)..."
"$VENV/bin/pip" install -q -r "$PROJECT_DIR/requirements.txt"

# 2. Models ---------------------------------------------------------------
# The dlib ResNet-50 embedding, 5-point and 68-point landmark models ship
# inside the face_recognition_models package. Only YuNet (better low-light
# detection) is fetched separately.
mkdir -p "$MODELS_DIR"
YUNET="$MODELS_DIR/face_detection_yunet_2023mar.onnx"
if [ ! -f "$YUNET" ]; then
    echo "[2/4] Downloading YuNet DNN face detector (~230 KB)..."
    curl -L --fail -sS -o "$YUNET" \
        "https://github.com/opencv/opencv_zoo/raw/main/models/face_detection_yunet/face_detection_yunet_2023mar.onnx" \
        || { echo "      (download failed - will use dlib HOG detector)"; rm -f "$YUNET"; }
else
    echo "[2/4] YuNet model already present."
fi

# 3. Launcher scripts -----------------------------------------------------
echo "[3/4] Writing launcher scripts to $BIN_DIR"
mkdir -p "$BIN_DIR"

write_launcher() {
    local name="$1" extra="$2"
    cat > "$BIN_DIR/$name" <<EOF
#!/bin/zsh
# FaceSudo launcher (generated by install.sh)
export PYTHONPATH="$PROJECT_DIR:\$PYTHONPATH"
exec "$VENV/bin/python" -m facesudo $extra "\$@"
EOF
    chmod +x "$BIN_DIR/$name"
}

write_launcher "facesudo" ""
write_launcher "facesudo-auth" "auth"
write_launcher "facesudo-settings" "gui"
write_launcher "facesudo-menu" "menu"

# 4. .zshrc wrapper -------------------------------------------------------
echo "[4/4] Installing .zshrc sudo wrapper"
ZSHRC="$HOME/.zshrc"
MARKER_IN="# >>> FaceSudo >>>"
MARKER_OUT="# <<< FaceSudo <<<"

read -r -d '' BLOCK <<EOF || true
$MARKER_IN
export PATH="\$HOME/.facesudo/bin:\$PATH"
sudo() {
  if [[ -z "\$FACESUDO_NO" && -t 0 ]] && command -v facesudo-auth >/dev/null 2>&1; then
    if ! /usr/bin/sudo -n true 2>/dev/null; then
      facesudo-auth "\$@"
      return \$?
    fi
  fi
  command sudo "\$@"
}
$MARKER_OUT
EOF

if [ -f "$ZSHRC" ] && grep -qF "$MARKER_IN" "$ZSHRC"; then
    awk -v inmark="$MARKER_IN" -v outmark="$MARKER_OUT" '
        $0 == inmark { skip = 1 }
        $0 == outmark { skip = 0; print; next }
        !skip { print }
    ' "$ZSHRC" > "$ZSHRC.facesudo.tmp" && mv "$ZSHRC.facesudo.tmp" "$ZSHRC"
    echo "      replaced previous FaceSudo block in $ZSHRC"
else
    printf '\n%s\n' "$BLOCK" >> "$ZSHRC"
    echo "      appended FaceSudo block to $ZSHRC"
fi

echo
echo "== Done. Next steps =="
echo "  1.  new terminal, or:  source ~/.zshrc"
echo "  2.  store your sudo password in the Keychain:"
echo "        facesudo set-password"
echo "  3.  enroll your face:"
echo "        facesudo enroll          (CLI, guided)"
echo "        facesudo-settings        (GUI settings + guided enrollment)"
echo "  4.  test a match:"
echo "        facesudo verify"
echo "  5.  try it:"
echo "        sudo whoami"
echo
echo "If dlib failed to compile, install.sh reports it via 'facesudo status'"
echo "(engine: unavailable). In that case run 'facesudo test-camera' and see the"
echo "README for the mediapipe fallback."
